export enum DisruptionReason{
  CANCELATION_NOTICE_UNDER_14_DAYS = 'CANCELATION_NOTICE_UNDER_14_DAYS',
  CANCELATION_ON_DAY_OF_DEPARTURE = 'CANCELATION_ON_DAY_OF_DEPARTURE',
  ARRIVED_3H_LATE = 'ARRIVED_3H_LATE',
  NEVER_ARRIVED = 'NEVER_ARRIVED',
  DID_NOT_GIVE_THE_SEAT_VOLUNTARILY = 'DID_NOT_GIVE_THE_SEAT_VOLUNTARILY',
}
