export enum DisruptionReasons {
  CANCELLATION_UNDER_14_DAYS_AND_OVER_3H = 'CANCELLATION_UNDER_14_DAYS_AND_OVER_3H',
  CANCELLATION_UNDER_14_DAYS_AND_NEVER_ARRIVED = 'CANCELLATION_UNDER_14_DAYS_AND_NEVER_ARRIVED',
  CANCELLATION_ON_DAY_OF_DEPARTURE_AND_OVER_3H = 'CANCELLATION_ON_DAY_OF_DEPARTURE_AND_OVER_3H',
  CANCELLATION_ON_DAY_OF_DEPARTURE_AND_NEVER_ARRIVED = 'CANCELLATION_ON_DAY_OF_DEPARTURE_AND_NEVER_ARRIVED',
  ARRIVED_3H_LATE = 'ARRIVED_3H_LATE',
  NEVER_ARRIVED = 'NEVER_ARRIVED',
  OVERBOOKING = 'OVERBOOKING',
  DENIED_BOARDING_WITHOUT_REASON = 'DENIED_BOARDING_WITHOUT_REASON',
  NOT_ELIGIBLE_REASON = 'NOT_ELIGIBLE_REASON',
  CONDITIONS_NOT_FULFILLED = 'CONDITIONS_NOT_FULFILLED',
}
