package com.airassist.backend.model.enums;

public enum DisruptionReasons {
    CANCELLATION_UNDER_14_DAYS_AND_OVER_3H,
    CANCELLATION_UNDER_14_DAYS_AND_NEVER_ARRIVED,
    CANCELLATION_ON_DAY_OF_DEPARTURE_AND_OVER_3H,
    CANCELLATION_ON_DAY_OF_DEPARTURE_AND_NEVER_ARRIVED,
    ARRIVED_3H_LATE,
    NEVER_ARRIVED,
    OVERBOOKING,
    DENIED_BOARDING_WITHOUT_REASON,
    OTHER
}
