package com.airassist.backend.model.enums;

public enum DisruptionReasons {
    CANCELATION_NOTICE_UNDER_14_DAYS,
    CANCELATION_NOTICE_OVER_14_DAYS,
    CANCELATION_ON_DAY_OF_DEPARTURE,
    ARRIVED_3H_LATE,
    ARRIVED_EARLY,
    NEVER_ARRIVED,
    DID_NOT_GIVE_THE_SEAT_VOLUNTARILY,
    DID_GIVE_THE_SEAT_VOLUNTARILY,
}
